### ISSUE TITLE
Missing release changlog

### ISSUE THREAD

**Issue by ZayneLiu** [sapics/ip-location-api#11]
@sapics 

The other day I was going through packages, I noticed the version of this package got bumped, having no knowledge of what's changed, I could not be sure whether to update.

Then I noticed you were manually incrementing the version number, which got me thinking if we could automate this process, I had a look around, and [release-it](https://github.com/release-it/release-it) came up.

It has a interactive UI, and automates most of tasks involved.
- Auto versioning
- Generating changelog
- Publish to npm
- Publish release Github
- etc.

Usage is very straightforward, 
- `npm login`
- and just run `npm run release`

Do you think this would be a good idea?

**Comment by sapics** [comment]
Looks great!!!!

**Comment by ZayneLiu** [comment]
#12

**Comment by sapics** [comment]
Thanks!! It helps me ;)
