### ISSUE TITLE
Add a `silent` option or use debug package

### ISSUE THREAD

**Issue by Bas950** [sapics/ip-location-api#4]
Either add a `silent` option, or use [debug](https://www.npmjs.com/package/debug) so we can enable the debug logs in environment variables or using settings.

Tip:  if you go with [debug](https://www.npmjs.com/package/debug) (my preference), you should probably run `debug.enable('ip-location-api')` when using the CLI, so if you use the CLI you still get logs.

If you want, I can also PR this.

**Comment by sapics** [comment]
Indeed! It is good feature!

I use the console.log result for updating the database.
It is bit complicated, thus, I will fix by myself.

**Comment by sapics** [comment]
Thanks for feature request!
Now, I add `ILA_SILENT` option in newer version. Could you try to test?

**Comment by sapics** [comment]
I close this issue because there has been no response. If you have any issues, feel free to reopen this issue or create new issue.
