### ISSUE TITLE
db.cjs file syntax error

### ISSUE THREAD

**Issue by LucyEgan** [sapics/ip-location-api#8]
In the file
https://github.com/sapics/ip-location-api/blob/4c6ae3c97c9d100b27ff0341f8dc1d7789520c94/cjs/db.cjs#L7

The following syntax is broken
`const { pipeline } = require('stream/promises';)` -> `const { pipeline } = require('stream/promises');`

**Comment by sapics** [comment]
Thanks for notice @LucyEgan ! I have fixed in newer version!
