### ISSUE TITLE
No such file or directory , mkdir /vercel

### ISSUE THREAD

**Issue by indrasenareddy91** [sapics/ip-location-api#9]
hey there this issue is not fully resolved
using it in nextjs 15
installed ur latest package via npm
used this..
import { lookup } from 'ip-location-api/pack'
even just importing this is causing the error [ spent 2 hours finding what is causing the error]
[sorry about the other comment i looked into another deployment logs and taught it was working]
![380781698-fea6c172-8193-46f1-bbd0-fb16ee1e623b](https://github.com/user-attachments/assets/23d7593b-8e84-4864-94dc-2baa674d150f)

**Comment by sapics** [comment]
I guess that there are not write permission to `/vercel`. Please write down your environment setting.
With the settings unknown, it is not possible to investigate anything further.

I hard that you have succeeded with the other module. Could you tell me the module?

**Comment by indrasenareddy91** [comment]
it's not actually a module it's ab api
environment setting??? 
like package.json Or where I deployed my website ?[ it's on vercel itself]
Using lastes nextjs 15,react 19

**Comment by sapics** [comment]
Please write down your configuration in [README-conf](https://github.com/sapics/ip-location-api?tab=readme-ov-file#setup-the-configuration).
At least, you need to configure write permission folder as [README-pack](https://github.com/sapics/ip-location-api?tab=readme-ov-file#for-module-bundler-webpack-vite-nextjs-etc).

**Comment by indrasenareddy91** [comment]
Since vercel is serverless
The filesystem is read-only in production
also The environment is temporary - any files written during execution don't persist between requests
We cannot create or write to directories in the `/vercel` path

**Comment by sapics** [comment]
If there are no write permission directories, this module could not work.
